version: "2"

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'redis:4-alpine'
    command: redis-server --requirepass redis_password
    ports:
      - '6379:6379'

  memcached:
    image: 'bitnami/memcached:latest'
    ports:
      - '11211:11211'
    networks:
      - app-tier

